version: '3'
services:
    python3:
        build: .
        container_name: 'alpha_zero'
        working_dir: /work/
        command: /bin/sh -c "while sleep 1000; do :; done"
        volumes:
            - .:/work:cached
            - python-packages:/root/.local/share
volumes:
  python-packages: